const MENTION_DEFAULT_FILE_ICON = "";
const MENTION_NON_TEXT_FILE_ICON = "";
const MENTION_NON_TEXT_EXTENSIONS: ReadonlySet<string> = new Set([
	"7z",
	"a",
	"bin",
	"class",
	"dmg",
	"dll",
	"exe",
	"gz",
	"iso",
	"jar",
	"o",
	"obj",
	"pdf",
	"so",
	"tar",
	"wasm",
	"xz",
	"zip",
]);

const MENTION_FILE_ICONS_BY_NAME: Readonly<Record<string, string>> = {
	config: "󱁻",
	license: "",
	"license.md": "",
	markdown: "",
	html: "",
	css: "",
	"c++": "",
	"c#": "",
	python: "",
	rust: "",
	php: "",
	elixir: "",
	zig: "",
	solidity: "",
	graphql: "",
	terraform: "",
	nix: "",
	groovy: "",
	"f#": "",
	docker: "",
	composer: "",
	prettier: "",
	deno: "",
	txt: "",
	csv: "",
	log: "",
	font: "",
	folder: "󰉋",
	".gitignore": "",
	".gitattributes": "",
	".gitmodules": "",
	commit_editmsg: "",
	"package.json": "",
	"package-lock.json": "",
	"npm-shrinkwrap.json": "",
	".npmrc": "",
	".npmignore": "",
	"composer.json": "",
	"composer.lock": "",
	"pnpm-lock.yaml": "",
	"pnpm-workspace.yaml": "",
	"yarn.lock": "",
	".yarnrc": "",
	".yarnrc.yml": "",
	"tsconfig.json": "",
	"jsconfig.json": "",
	".git": "",
	".github": "",
	".vscode": "",
	".editorconfig": "",
	".dockerignore": "",
	"dockerfile": "",
	"docker-compose.yml": "",
	"docker-compose.yaml": "",
	"compose.yml": "",
	"compose.yaml": "",
	"makefile": "",
	"gnumakefile": "",
	"cmake": "",
	"cmakelists.txt": "",
	".netlify": "",
	mcp: "󰚩",
	"mcp.json": "󰚩",
	prisma: "",
	"tailwind.config.js": "󱏿",
	"tailwind.config.cjs": "󱏿",
	"tailwind.config.mjs": "󱏿",
	"tailwind.config.ts": "󱏿",
	"angular.json": "",
	"astro.config.js": "",
	"astro.config.mjs": "",
	"next.config.js": "",
	"next.config.mjs": "",
	"next.config.ts": "",
	"jquery.js": "",
	"tauri.conf.json": "",
	"bun.lock": "",
	"bun.lockb": "",
	"bunfig.toml": "",
	"deno.json": "",
	"deno.jsonc": "",
	"deno.lock": "",
	".prettierrc": "",
	".prettierrc.json": "",
	".prettierrc.js": "",
	".prettierrc.cjs": "",
	".prettierrc.mjs": "",
	".prettierrc.yaml": "",
	".prettierrc.yml": "",
	".prettierrc.toml": "",
	"prettier.config.js": "",
	"prettier.config.cjs": "",
	"prettier.config.mjs": "",
	"prettier.config.ts": "",
	"nginx.conf": "",
	"wrangler.toml": "",
	"wrangler.json": "",
	"wrangler.jsonc": "",
	"cloudflare.toml": "",
	"netlify.toml": "",
	"vitest.config.js": "",
	"vitest.config.ts": "",
	"vitest.config.mjs": "",
	"vite.config.js": "",
	"vite.config.ts": "",
	"vite.config.mjs": "",
	"vercel.json": "",
	"pyproject.toml": "",
	"poetry.lock": "",
	"nest-cli.json": "",
	"nuxt.config.js": "",
	"nuxt.config.ts": "",
	"gatsby-config.js": "",
	"gatsby-config.ts": "",
	"gatsby-node.js": "",
	"three.js": "",
	"postman_collection.json": "",
	"postman_environment.json": "",
	artisan: "",
	"electron-builder.yml": "",
	"playwright.config.js": "",
	"playwright.config.ts": "",
	"playwright.config.mjs": "",
	powershell: "",
	bat: "",
	test: "󰙨",
	tailwind: "󱏿",
	react: "",
	vuejs: "",
	astro: "",
	angular: "",
	nextjs: "",
	svelte: "",
	jquery: "",
	qt: "",
	vim: "",
	bun: "",
	less: "",
	bash: "",
	tauri: "",
	swift: "",
	nuget: "",
	nginx: "",
	godot: "",
	flask: "",
	vscode: "",
	vitest: "",
	vite: "",
	vercel: "",
	stylus: "",
	sqlite: "",
	spring: "",
	sentry: "",
	poetry: "",
	nestjs: "",
	nuxtjs: "",
	gatsby: "",
	threejs: "",
	postman: "",
	mongo: "",
	laravel: "",
	blender: "",
	electron: "",
	playwright: "",
	".vercel": "",
	".sentryclirc": "",
};

const MENTION_FILE_ICONS_BY_EXTENSION: Readonly<Record<string, string>> = {
	md: "",
	markdown: "",
	html: "",
	htm: "",
	css: "",
	scss: "",
	less: "",
	styl: "",
	cpp: "",
	cxx: "",
	cc: "",
	cp: "",
	cs: "",
	js: "",
	jsx: "",
	mjs: "",
	cjs: "",
	ts: "",
	tsx: "",
	mts: "",
	cts: "",
	py: "",
	pyw: "",
	rs: "",
	php: "",
	txt: "",
	json: "",
	json5: "",
	jsonc: "",
	go: "󰟓",
	lua: "󰢱",
	luau: "󰢱",
	kt: "󱈙",
	kts: "󱈙",
	java: "",
	sql: "",
	toml: "",
	mp3: "",
	wav: "",
	flac: "",
	m4a: "",
	ogg: "",
	opus: "",
	mp4: "",
	mkv: "",
	avi: "",
	mov: "",
	webm: "",
	mpeg: "",
	mpg: "",
	wmv: "",
	flv: "",
	png: "",
	jpg: "",
	jpeg: "",
	gif: "",
	bmp: "",
	ico: "",
	webp: "",
	svg: "",
	tiff: "",
	avif: "",
	ps1: "",
	psm1: "",
	bat: "",
	cmd: "",
	test: "󰙨",
	prisma: "",
	astro: "",
	vue: "",
	svelte: "",
	ui: "",
	vim: "",
	swift: "",
	nuspec: "",
	nupkg: "",
	gd: "",
	sqlite: "",
	sqlite3: "",
	db3: "",
	blend: "",
	playwright: "",
	mongodb: "",
	bash: "",
	tauri: "",
	nginx: "",
	flask: "",
	vitest: "",
	vite: "",
	vercel: "",
	stylus: "",
	xml: "󰗀",
	yaml: "",
	yml: "",
	conf: "",
	j2: "",
	jinja: "",
	jinja2: "",
	ex: "",
	exs: "",
	eex: "",
	leex: "",
	heex: "",
	zig: "",
	sol: "",
	graphql: "",
	gql: "",
	graphqls: "",
	tf: "",
	tfvars: "",
	tfstate: "",
	hcl: "",
	nix: "",
	groovy: "",
	gvy: "",
	gy: "",
	gsh: "",
	gradle: "",
	fs: "",
	fsi: "",
	fsx: "",
	fsscript: "",
	fsproj: "",
	dockerfile: "",
	mk: "",
	cmake: "",
	composer: "",
	editorconfig: "",
	prettierrc: "",
	prettier: "",
	deno: "",
	bun: "",
	csv: "",
	tsv: "",
	log: "",
	ttf: "",
	otf: "",
	woff: "",
	woff2: "",
	eot: "",
	fon: "",
};

export {
	MENTION_DEFAULT_FILE_ICON,
	MENTION_FILE_ICONS_BY_EXTENSION,
	MENTION_FILE_ICONS_BY_NAME,
	MENTION_NON_TEXT_EXTENSIONS,
	MENTION_NON_TEXT_FILE_ICON,
};
